### ISSUE TITLE
Not counting

### ISSUE THREAD

**Issue by pizzamaker** [emijrp/wmcounter#2]
wmcounter is... not counting: https://tools.wmflabs.org/wmcounter/

**Comment by misc544** [comment]
Yes I’m trying to access it but I don’t see the number. C’mon

**Comment by misc544** [comment]
Hmm I might experiment with this... I’m going to create a fork to dandom 2020.

**Comment by misc544** [comment]
I think it reached some limit error thingy

**Comment by misc544** [comment]
no The problem’s in the css code, and no source of number thingy: @emijrp @pizzamaker

**Comment by emijrp** [comment]
It's back.

I had to restart webservice.
